spring:
  application:
    name: football-attendance
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./football_attendance.db
  sql:
    init:
      mode: always

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
